### ISSUE TITLE
Two tips.....

### ISSUE THREAD

**Issue by PySimpleGUI** [LuizMeraki/ArchiveOrganizer#1]
Jump stumbled into your repo and thought of a couple of tips you may benefit from.

One is a screenshot in your readme.

https://pysimplegui.readthedocs.io/en/latest/cookbook/#recipe-post-your-screen-shots-please

Another is your icon.  I like that you used `set_options` to set an icon for your entire application.

![image](https://user-images.githubusercontent.com/46163555/152353779-47204fb2-ca8e-4575-8c75-a3ed91b1df79.png)

Bravo!

An icon file can be tricky because it's another file that could get lost.  In fact, I wasn't able to locate your icon file in your repo:
https://github.com/LuizMeraki/ArchiveOrganizer/blob/8123193e4cd5317a28455704bae3de6a213fc7de/Archive%20Organizer/Codes/ArchiveOrganizer.py#L5

The way around this is to convert a PNG version of your icon file into a Base64 string and paste the entire string into your .py file.  This is what I do with all of the demos, sample programs, PySimpleGUI itself, etc.

There is a newish tool released last year to help you.  If you pip install psgresizer than you'll get a tool that will not only convert between file formats, it'll convert into Base64 so that you can paste the string into your code.

Here it is running:
![image](https://user-images.githubusercontent.com/46163555/152354676-9672b076-f5c5-490a-8cff-33d8a827def6.png)

I concerted an ICO file in this example into a Base64 encoded PNG file that I then pasted into my code and then set the icon to that value so that my windows use it.

![image](https://user-images.githubusercontent.com/46163555/152354895-32bbc1b8-1315-4b22-ba9d-c09fa4e062e5.png)

```python
    sg.set_options(icon=icon)
```

Great stuff you're doing!

**Comment by LuizMeraki** [comment]
I am really very happy to receive this support from you. Leave it to me to solve it!

**Comment by PySimpleGUI** [comment]
Awesome!  I'm **sure** you'll handle things easily.

There is a Python group on Facebook from Brazil that I'm aware of you may find interesting.  PySimple GUI has a LOT of users in Brazil which is awesome, but it is puzzling.  Happy to have users from everywhere!

**Comment by LuizMeraki** [comment]
Thank you very much!<3
